# Generated by Django 5.0.3 on 2024-03-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addressdetails_first_time_bankdetails_first_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=30, null=True),
        ),
    ]
